React tabs with router
mate-academy/react_tabs-with-router pull request #339
Opened 2022-07-22 16:27 UTC by vsupruniuk

[DEMO LINK](https://vsupruniuk.github.io/react_tabs-with-router/)

2022-08-02 12:41 UTC, jstmpelowycz requested changes

2022-08-02 12:41 UTC, jstmpelowycz commented on src/App.tsx
> +        <Route path="/tabs/:tabId" element={<TabsPage />} />
you'd rather use nested routes

2022-08-02 12:41 UTC, jstmpelowycz commented on src/Components/Navigation/Navigation.tsx
> +          ))}
looks like a separate callback

2022-08-02 12:41 UTC, jstmpelowycz commented on src/Components/TabsPage/TabsPage.tsx
> +  const getContent = (tabId: string | undefined) => {
```suggestion
  const getContent = (tabId?: string) => {
```

2022-08-02 12:41 UTC, jstmpelowycz commented on src/Components/TabsPage/TabsPage.tsx
> +  const match = useMatch('/tabs/:tabId');
you'd rather apply `useParams`

2022-08-02 14:59 UTC, jstmpelowycz requested changes

2022-08-03 08:22 UTC, vsupruniuk commented on src/Components/Navigation/Navigation.tsx
> +    return 'nav-link';
👀

2022-08-03 13:57 UTC, jstmpelowycz approved these changes

2022-08-03 13:57 UTC, jstmpelowycz commented on src/Components/Navigation/Navigation.tsx
> +  const createClassNames = ({ isActive }: { isActive: boolean }) => {
:harold:

2024-02-11 13:29 UTC, closed without merging