sol
mate-academy/react_tabs-with-router pull request #373
Opened 2022-08-03 05:37 UTC by KrisMur

[DEMO LINK](https://KrisMur.github.io/react_tabs-with-router/)

2022-08-03 07:27 UTC, jstmpelowycz requested changes

2022-08-03 07:27 UTC, jstmpelowycz commented on src/App.tsx
> +        </NavLink>
review the checklist, p.1

2022-08-03 07:27 UTC, jstmpelowycz commented on src/App.tsx
> +          element={<Tabs tabs={tabs} selectedTabId={selectedTab?.id} />}
you shouldn't pass tab id, use routes hooks to retrieve what you need

2022-08-03 07:27 UTC, jstmpelowycz commented on src/App.tsx
> +                selectedTab={selectedTab}
with tab – as well

2022-08-03 07:27 UTC, jstmpelowycz commented on src/conponents/TabsPage.tsx
> +import { tabs } from '../api/tabs';
pass them as props

2022-08-08 10:15 UTC, mykola-koval approved these changes

2024-10-19 12:32 UTC, closed without merging