Solution
mate-academy/react_tabs-with-router pull request #39
Opened 2019-09-30 12:46 UTC by KosBelozyorov

[DEMO LINK](https://KosBelozyorov.github.io/react_tabs-with-router/)

2019-09-30 13:24 UTC, danheim requested changes

2019-09-30 13:24 UTC, danheim commented on src/App.js
> +        <BrowserRouter basename={process.env.PUBLIC_URL}>
можно использовать `HashRouter`, а в целом круто, что добавил `basename`

2019-09-30 13:24 UTC, danheim commented on src/App.js
> +      <div className="App">
зачем нам класс `App`?

2019-09-30 13:24 UTC, danheim commented on src/App.js
> +            exact
`exact` тут не нужен

2019-09-30 13:24 UTC, danheim commented on src/components/Tab/Tab.css
> +.tabs-list a {
стилизуем классы, не теги

2019-09-30 13:24 UTC, danheim commented on src/components/TabsPage/TabsPage.js
> +  constructor(props) {
нам не нужен здесь конструктор

2019-09-30 13:24 UTC, danheim commented on src/components/TabsPage/TabsPage.js
> +    const { onClickTabItem } = this;
не деструктурируем методы класса

2019-09-30 13:24 UTC, danheim commented on src/components/TabsPage/TabsPage.js
> +
если все деструктуризации идут в одну строку, отступ не нужен

2019-09-30 14:08 UTC, KosBelozyorov commented
Fixed

2019-10-01 14:24 UTC, danheim requested changes
Задача научиться пользоваться роутером:
1. Классы в этом задании не нужны
2. Не используй `render`, используй `component`
3. Компонент должен брать `id` таба из адресной строки

2019-10-01 14:24 UTC, danheim commented on src/App.js
> +  state = {
состояние может меняться, но не в этом задании
нам не нужен `class` и `state`

2019-10-01 14:24 UTC, danheim commented on src/App.js
> +      <BrowserRouter basename={process.env.PUBLIC_URL}>
мне нравится

2019-10-01 14:24 UTC, danheim commented on src/App.js
> +          render={({ match }) => <TabsPage match={match} tabs={tabs} />}
попробуй просто через компонент, без `render`, а массив с табами создай в компоненте `TabsPage`

2019-10-01 14:24 UTC, danheim commented on src/components/TabsPage/TabsPage.js
> +    currentTabId: '',
не должно быть состояния и тем более `currentTabId`, компонент должен понимать какой контент рендерить взяв `tabid` из адресной строки

2019-10-01 14:24 UTC, danheim commented on src/components/TabsPage/TabsPage.js
> +  onClickTabItem = id => this.setState({ currentTabId: id });
remove

2019-10-01 14:24 UTC, danheim commented on src/components/TabsPage/TabsPage.js
> +class TabsPage extends Component {
`class` нам тут не нужен соответственно

2019-10-02 12:25 UTC, KosBelozyorov commented
Fixed

2019-10-02 14:28 UTC, danheim approved these changes

2019-10-02 14:28 UTC, danheim commented on src/components/TabsPage/TabsPage.js
> +  const { tabs, currentTabId } = props;
стрелочная функция + деструктуризация в аргументах функции

2019-10-02 14:28 UTC, danheim commented on src/components/Tab/Tab.js
> +}) => {
`const tab = ({ id, title, isActive }) => {` поместится в одну строку

2019-10-02 14:28 UTC, danheim commented on src/components/TabsPage/TabsPage.js
> +        {tabs.map(({ id, content }) => {
альтернативой может быть метод `find`

2025-09-21 20:36 UTC, closed without merging