silution
mate-academy/react_tabs-with-router pull request #693
Opened 2023-04-11 12:20 UTC by Zelinskyi-Serhii

solution*
[DEMO LINK](https://<your_account>.github.io/react_tabs-with-router/)

2023-04-11 14:28 UTC, rashyd-hasratov requested changes
Good job! You just forgot to add README (DEMO LINK doesn't work) and also I left one more suggestion below

2023-04-11 14:28 UTC, rashyd-hasratov commented on src/TabItem/TabItem.tsx
> +    </Link>
Let`s use destructuring for tab

2023-04-19 16:01 UTC, OleksiiBlezniuk approved these changes

2023-04-19 16:01 UTC, OleksiiBlezniuk commented on src/TabsPage/TabsPage.tsx
> +        ) }
```suggestion
        {activeTad
          ? (
            activeTad.content
          )
          : (
            'Please select a tab'
          ) }
```

2023-04-19 16:01 UTC, OleksiiBlezniuk commented on src/TabsPage/TabsPage.tsx
> +  const activeTad = tabs.find(tab => tab.id === tabId);
```suggestion
  const activeTab = tabs.find(tab => tab.id === tabId);
```

2023-04-19 16:01 UTC, OleksiiBlezniuk commented on src/TabsPage/TabsPage.tsx
> +  const { tabId } = useParams();
better to create type for params and pass it as generic here

2023-07-12 19:51 UTC, closed without merging