add tabs-with-router
mate-academy/react_tabs-with-router pull request #846
Opened 2023-06-26 14:43 UTC by DidenkoDenis306

[DEMO LINK](https://DidenkoDenis306.github.io/react_tabs-with-router/)

2023-06-29 12:37 UTC, 33Orange requested changes
Almost done.

A few moments to improve

2023-06-29 12:37 UTC, 33Orange commented on src/App.tsx
> +        </Routes>
1. Let's create a component `Layout`. 
2. Wrap all your routes to `layout route`. 
3. This layout component should render a `Navigation` and wrap content to section. You can use Outlet from react-router-dom.

```
  <main className="section">
    <Outlet />
  </main>
```

```suggestion
<Routes>
  <Route path="/" element={<Layout />}>
    .. homepage
    ...tabs
    .. etc
</Routes>     
```

2023-06-29 12:37 UTC, 33Orange commented on src/components/Tabs/Tabs.tsx
> +    <>
Use some semantic element instead of react fragment. You have container for this content

```suggestion
   <div className="container">
```

2023-06-29 12:37 UTC, 33Orange commented on src/pages/TabsPage.tsx
> +  <>
Same here

2023-07-07 07:09 UTC, skinnyjazz approved these changes
Look like strong and clean code!

2024-07-09 10:12 UTC, closed without merging