solution
mate-academy/react_tabs-with-router pull request #870
Opened 2023-07-09 18:49 UTC by PanyaPrimal

2023-07-10 12:50 UTC, maryanmats approved these changes
Good job!)

2023-07-11 10:43 UTC, dinaminahi requested changes
Almost done
Let's do few fixes

2023-07-11 10:43 UTC, dinaminahi commented on src/App.tsx
>        <div className="container">
Put nav to a Navigation component and create a Layout component that will serve as a wrapper for all your routes. Within this Layout, we'll include a Navigation component and a section to wrap the content. To achieve this, we can use the Outlet component from react-router-dom.

```
<Routes>
  <Route path="/" element={<Layout />}>
    .. homepage
    ...tabs
    ...
 </Routes>   
```

2023-07-11 10:43 UTC, dinaminahi commented on src/App.tsx
> +];
Let's move it to a TabsPage component

2025-12-18 12:02 UTC, closed without merging