Solution
mate-academy/react_tabs-with-router pull request #900
Opened 2023-07-12 09:00 UTC by bohdan-mykhailenko

[DEMO LINK](https://bohdan-mykhailenko.github.io/react_tabs-with-router/)

2023-07-14 15:37 UTC, Moroz-Dmytro requested changes
LGTM 🔥 
Only small comments

2023-07-14 15:37 UTC, Moroz-Dmytro commented on src/pages/NotFound/NotFound.tsx
> +export const NotFound: React.FC = () => (
```suggestion
export const NotFoundPage: React.FC = () => (
```

2023-07-14 15:37 UTC, Moroz-Dmytro commented on src/pages/Tabs/Tabs.tsx
> +];
Move it to `constants` file

2023-07-14 15:37 UTC, Moroz-Dmytro commented on src/pages/Tabs/Tabs.tsx
> +          : 'Please select a tab'}
```suggestion
        { selectedTab?.content || 'Please select a tab'}
```

2023-07-14 15:37 UTC, Moroz-Dmytro commented on src/components/TabItem/TabItem.tsx
> +  tabId: string | undefined;
Better to name this `selectedTabId` and use `null` as default value instead of `undefined` if tab is not selected

2023-07-17 13:11 UTC, dinaminahi approved these changes
Well done 👍

2024-08-02 22:05 UTC, closed without merging